name: Generate requirements.txt and push changes

on:
  push:
    branches:
      - main  # Replace 'main' with your primary branch name

jobs:
  generate-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace '3.x' with your Python version

      - name: run main.py
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python main.py
