name: Update

on:
  push:
    branches:
      - main

jobs:
  update-requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version here
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          python -m pip freeze > requirements.txt.new
          mv requirements.txt.new requirements.txt
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add requirements.txt
          git commit -m "Update requirements.txt by GitHub Actions" 
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: run main file
        run: |
          python -m pip install -r requirements.txt
          python main.py register.py form_filler.py
