name: Update requirements and push changes

on:
  push:
    paths:
      - '**.py'  # Triggers on any changes to Python files
      - 'requirements.txt'  # Triggers on changes to requirements.txt

jobs:
  update-requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version here

      - name: Upgrade pip and update requirements.txt
        run: |
          python -m pip install --upgrade pip
          python -m pip freeze > requirements.txt

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add requirements.txt
          git commit -m "Update requirements.txt by GitHub Actions"
        
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
