name: Update requirements

on:
  push:
    paths:
      - '**.py'  # Triggers on any changes to Python files
      # Add other relevant paths if necessary

jobs:
  update-requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version here

      - name: Install pip
        run: |
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip

      - name: Generate requirements.txt
        run: |
          python -m pip freeze > requirements.txt

      - name: Check for changes in requirements.txt
        id: check_changes
        run: |
          git diff-index --quiet HEAD || echo "Changes detected"

      - name: Commit changes if any
        if: steps.check_changes.outputs.run != 'Changes detected'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add requirements.txt
          git commit -m "Update requirements.txt by GitHub Actions"

      - name: Push changes
        if: steps.check_changes.outputs.run != 'Changes detected'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
