name: Generate requirements.txt and push changes

on:
  push:
    branches:
      - main  # Replace 'main' with your primary branch name

jobs:
  generate-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace '3.x' with your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate requirements.txt
        run: |
          pip freeze > requirements.txt

      - name: Check for changes in requirements.txt
        id: git-check
        run: |
          git diff --exit-code --quiet || (echo "Changes detected in requirements.txt"; exit 1)

      - name: Push changes to main branch
        if: ${{ github.ref == 'refs/heads/main' && steps.git-check.outcome == 'success' }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add requirements.txt
          git commit -m "Update requirements.txt"
          git push https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
          pip install -r requirements.txt
          python main.py
          python form_filler.py
          python register.py

