name: Integration Test
on:
  push:
    branches:
      -main
  schedule:
      - cron: '0 0 30 12 *'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Automatic requirements.txt for Python Project
        uses: ryan-rozario/pipreqs-action@master

        # Put an example of mandatory inputs here
        with:
          REQUIREMENT_PATH: requirements.txt  #default is requirement.txt in the root of your repository 
