name: Update requirements.txt

on:
  push:
    branches:
      - main  # Update with your primary branch name

jobs:
  update-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace '3.x' with your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Update requirements.txt
        run: |
          # Add or update your dependencies as needed using pip
          pip install <package-name>
          # Or if you have a requirements.in file, update the requirements.txt using pip-compile
          # pip-compile requirements.in

          # After updating, display the contents of the updated requirements.txt
          cat requirements.txt

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add requirements.txt
          git commit -m "Update requirements.txt"
          git push
