name: Update Requirements

on:
  push:
    branches:
      - main

jobs:
  update-requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version here

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Generate updated requirements.txt
        run: |
          python -m pip freeze > requirements.txt.new

      - name: Replace requirements.txt with updated version
        run: |
          mv requirements.txt.new requirements.txt
